name: common-build

on:
  workflow_call:

jobs:
  build-and-upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Node.js Dependencies
        run: npm ci

      - name: Use Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode and save the keystore file
        run: |
          # Upload store file was encoded: base64 -i upload.keystore -o ~/upload.keystore.base64
          echo ${{ secrets.CONTEXT_LAUNCHER_UPLOAD_STORE_FILE }} | base64 --decode > $GITHUB_WORKSPACE/android/app/upload.keystore

      - name: Prepare local.properties file
        run: |
          # Since the password contains a dollar sign ($) I had to encode it and decode it here.
          STORE_PASSWORD=$(echo "${{ secrets.CONTEXT_LAUNCHER_UPLOAD_STORE_PASSWORD_BASE64 }}" | base64 --decode)
          KEY_PASSWORD=$(echo "${{ secrets.CONTEXT_LAUNCHER_UPLOAD_KEY_PASSWORD_BASE64 }}" | base64 --decode)
          echo "sdk.dir=$ANDROID_SDK_ROOT" > $GITHUB_WORKSPACE/android/local.properties
          echo "CONTEXT_LAUNCHER_UPLOAD_STORE_FILE=$GITHUB_WORKSPACE/android/app/upload.keystore" >> $GITHUB_WORKSPACE/android/local.properties
          echo "CONTEXT_LAUNCHER_UPLOAD_STORE_PASSWORD=$STORE_PASSWORD" >> $GITHUB_WORKSPACE/android/local.properties
          echo "CONTEXT_LAUNCHER_UPLOAD_KEY_ALIAS=${{ secrets.CONTEXT_LAUNCHER_UPLOAD_KEY_ALIAS }}" >> $GITHUB_WORKSPACE/android/local.properties
          echo "CONTEXT_LAUNCHER_UPLOAD_KEY_PASSWORD=$KEY_PASSWORD" >> $GITHUB_WORKSPACE/android/local.properties

      - name: Build
        working-directory: ./android
        run: ./gradlew --no-daemon build

      - name: Build Debug - APK
        working-directory: ./android
        run: ./gradlew --no-daemon assembleDebug

      - name: Build Release - APK & AAB
        working-directory: ./android
        run: |
          ./gradlew --no-daemon assembleRelease
          ./gradlew --no-daemon bundleRelease

      - name: Upload Debug & Release Binaries
        uses: actions/upload-artifact@v4
        with:
          name: context-launcher-debug-and-release-apk-and-aab
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
