name: main

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style-checks:
    uses: ./.github/workflows/code-style.yml
  unit-tests:
    uses: ./.github/workflows/tests.yml
    needs:
      - code-style-checks
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs:
      - unit-tests
