name: release

on:
  push:
    tags:
      - "*"

jobs:
  prepare-artifacts:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  create-release:
    runs-on: ubuntu-latest
    needs:
      - prepare-artifacts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: context-launcher-debug-and-release-apk-and-aab

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ./apk/**/*.apk
            ./bundle/**/*.aab
