name: Tests

on: [push]

jobs:
  jest-tests:
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:ci
